"""
Course / Lecture 초기 데이터 삽입
- 이미 데이터가 있으면 스킵 (idempotent)
- entrypoint 또는 POST /api/v1/crawl/seed-courses 로 실행
"""
import logging
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.models import Course, Lecture

logger = logging.getLogger(__name__)

_COURSES = [
    {
        "title": "선형대수학 (Linear Algebra)",
        "source": "MIT 18.06 · Gilbert Strang",
        "category": "math",
        "order_index": 1,
        "lectures": [
            "The Geometry of Linear Equations",
            "Elimination with Matrices",
            "Multiplication and Inverse Matrices",
            "Factorization into A = LU",
            "Transposes, Permutations, Spaces R^n",
            "Column Space and Nullspace",
            "Solving Ax = 0: Pivot Variables, Special Solutions",
            "Solving Ax = b: Row Reduced Form R",
            "Independence, Basis, and Dimension",
            "The Four Fundamental Subspaces",
            "Matrix Spaces; Rank 1; Small World Graphs",
            "Graphs, Networks, Incidence Matrices",
            "Quiz 1 Review",
            "Orthogonal Vectors and Subspaces",
            "Projections onto Subspaces",
            "Projection Matrices and Least Squares",
            "Orthogonal Matrices and Gram-Schmidt",
            "Properties of Determinants",
            "Determinant Formulas and Cofactors",
            "Cramer's Rule, Inverse Matrix, and Volume",
            "Eigenvalues and Eigenvectors",
            "Diagonalization and Powers of A",
            "Differential Equations and exp(At)",
            "Markov Matrices; Fourier Series",
            "Quiz 2 Review",
            "Symmetric Matrices and Positive Definiteness",
            "Complex Matrices; Fast Fourier Transform",
            "Positive Definite Matrices and Minima",
            "Similar Matrices and Jordan Form",
            "Singular Value Decomposition",
            "Linear Transformations and Their Matrices",
            "Change of Basis; Image Compression",
            "Quiz 3 Review",
            "Left and Right Inverses; Pseudoinverse",
        ],
    },
    {
        "title": "확률론과 통계",
        "source": "Stanford CS109 · 확률론 기초",
        "category": "stat",
        "order_index": 2,
        "lectures": [
            "Counting and Sets",
            "Probability Axioms",
            "Conditional Probability",
            "Independence and Bayes' Theorem",
            "Random Variables",
            "Discrete Distributions",
            "Continuous Distributions",
            "Normal Distribution",
            "Joint Distributions",
            "Expectation and Variance",
            "Covariance and Correlation",
            "Central Limit Theorem",
            "Maximum Likelihood Estimation",
            "Hypothesis Testing",
            "Confidence Intervals",
            "Bayesian Inference",
            "Markov Chains",
        ],
    },
    {
        "title": "머신러닝 기초",
        "source": "Stanford CS229 · Andrew Ng",
        "category": "ml",
        "order_index": 3,
        "lectures": [
            "Introduction and Linear Regression",
            "Gradient Descent",
            "Locally Weighted Regression and Logistic Regression",
            "Perceptron and Generalized Linear Models",
            "Gaussian Discriminant Analysis",
            "Naive Bayes",
            "Support Vector Machines",
            "SVM Kernels",
            "Neural Networks",
            "Bias/Variance Tradeoff",
            "Regularization and Model Selection",
            "Decision Trees and Ensemble Methods",
            "Random Forests and Boosting",
            "K-Means Clustering",
            "EM Algorithm",
            "Principal Component Analysis",
            "Independent Component Analysis",
            "Reinforcement Learning Introduction",
            "MDPs and Value Iteration",
            "Policy Gradient",
        ],
    },
    {
        "title": "딥러닝",
        "source": "deeplearning.ai · Andrew Ng",
        "category": "dl",
        "order_index": 4,
        "lectures": [
            "Neural Networks and Deep Learning",
            "Binary Classification and Logistic Regression",
            "Gradient Descent",
            "Vectorization",
            "Shallow Neural Networks",
            "Deep Neural Networks",
            "Practical Aspects: Train/Dev/Test Sets",
            "Bias and Variance",
            "Regularization",
            "Optimization Algorithms",
            "Hyperparameter Tuning",
            "Batch Normalization",
            "Convolutional Neural Networks",
            "Deep Convolutional Models",
            "Object Detection",
            "Face Recognition",
            "Sequence Models",
            "Recurrent Neural Networks",
            "Natural Language Processing with RNN",
            "Transformer Architecture",
            "Attention Mechanism",
            "BERT and GPT",
        ],
    },
    {
        "title": "컴퓨터 비전",
        "source": "Stanford CS231n · Fei-Fei Li",
        "category": "cv",
        "order_index": 5,
        "lectures": [
            "Introduction to Computer Vision",
            "Image Classification",
            "Loss Functions and Optimization",
            "Neural Networks",
            "Convolutional Neural Networks",
            "Training Neural Networks I",
            "Training Neural Networks II",
            "Deep Learning Software",
            "CNN Architectures: AlexNet, VGG, GoogLeNet, ResNet",
            "Recurrent Neural Networks",
            "Detection and Segmentation",
            "Visualizing and Understanding",
            "Generative Models: VAE, GAN",
            "Deep Reinforcement Learning",
            "Efficient Methods for Deep Learning",
            "Adversarial Examples and Robustness",
        ],
    },
    {
        "title": "자연어처리",
        "source": "Stanford CS224n · Christopher Manning",
        "category": "nlp",
        "order_index": 6,
        "lectures": [
            "Introduction and Word Vectors",
            "Word Vectors 2 and Word Senses",
            "Neural Classifiers",
            "Backpropagation",
            "Dependency Parsing",
            "Language Models and RNNs",
            "Vanishing Gradients, LSTMs, GRUs",
            "Seq2Seq, Attention",
            "Transformers",
            "Pretraining",
            "Question Answering",
            "Natural Language Generation",
            "Coreference Resolution",
            "T5 and Large Language Models",
            "Integrating Knowledge in Deep NLP",
            "Social and Ethical Considerations",
            "Future of NLP and DL",
        ],
    },
    {
        "title": "대규모 언어 모델 (LLM)",
        "source": "Stanford CS324 · DeepLearning.AI",
        "category": "llm",
        "order_index": 7,
        "lectures": [
            "Introduction to Large Language Models",
            "Tokenization and Vocabulary",
            "Pretraining Objectives and Data",
            "Transformer Architecture Deep Dive",
            "Scaling Laws",
            "Instruction Tuning",
            "RLHF: Reinforcement Learning from Human Feedback",
            "Prompt Engineering",
            "In-Context Learning and Few-Shot",
            "Retrieval-Augmented Generation (RAG)",
            "Fine-Tuning: Full vs. LoRA vs. QLoRA",
            "Evaluation: MMLU, HumanEval, MT-Bench",
            "Alignment and Safety",
            "Multimodal LLMs",
            "Agents and Tool Use",
            "Efficient Inference: Quantization and Distillation",
        ],
    },
    {
        "title": "강화학습",
        "source": "David Silver (UCL) · OpenAI Spinning Up",
        "category": "rl",
        "order_index": 8,
        "lectures": [
            "Introduction to Reinforcement Learning",
            "Markov Decision Processes",
            "Dynamic Programming",
            "Model-Free Prediction: Monte Carlo",
            "Model-Free Prediction: TD Learning",
            "Model-Free Control",
            "Value Function Approximation",
            "Policy Gradient Methods",
            "Actor-Critic Methods",
            "Integrating Learning and Planning",
            "Exploration vs. Exploitation",
            "Deep Q-Networks (DQN)",
            "Proximal Policy Optimization (PPO)",
            "Multi-Agent Reinforcement Learning",
            "RL in Real-World Applications",
        ],
    },
    {
        "title": "데이터 엔지니어링",
        "source": "DataTalks.Club · Zach Wilson",
        "category": "data",
        "order_index": 9,
        "lectures": [
            "Data Engineering Fundamentals",
            "Relational Databases and SQL",
            "NoSQL: Document, Column, Graph Stores",
            "Data Warehousing Concepts",
            "ETL vs. ELT Patterns",
            "Apache Spark: Basics",
            "Apache Spark: Advanced Operations",
            "Stream Processing with Kafka",
            "Apache Flink Fundamentals",
            "Airflow: DAG Orchestration",
            "dbt: Data Build Tool",
            "Data Lake and Lakehouse Architecture",
            "BigQuery and Snowflake",
            "Data Quality and Observability",
            "Building a Modern Data Stack",
        ],
    },
    {
        "title": "MLOps",
        "source": "Made With ML · Full Stack Deep Learning",
        "category": "mlops",
        "order_index": 10,
        "lectures": [
            "Introduction to MLOps",
            "Experiment Tracking with MLflow",
            "Data Versioning with DVC",
            "Feature Stores",
            "Model Training Pipelines",
            "Model Registry and Versioning",
            "Model Serving: REST APIs",
            "Model Serving: Batch Inference",
            "Containerization with Docker",
            "Kubernetes for ML Workloads",
            "CI/CD for Machine Learning",
            "Model Monitoring and Drift Detection",
            "A/B Testing and Canary Deployments",
            "Kubeflow Pipelines",
            "Cost Optimization in MLOps",
        ],
    },
    {
        "title": "보험계리학 (Actuarial Science)",
        "source": "SOA 시험 준비 · 계리 수학 기초",
        "category": "actuary",
        "order_index": 11,
        "lectures": [
            "보험계리학 개요 및 SOA 시험 체계",
            "Exam P: 확률론 기초",
            "Exam FM: 이자론 (Theory of Interest)",
            "Exam FM: 채권 및 투자",
            "Exam MFE: 금융경제학",
            "Exam LTAM: 생명보험수학 기초",
            "생명표와 사망률 분석",
            "순보험료와 영업보험료",
            "책임준비금 계산",
            "Exam STAM: 손해보험 단기 모형",
            "손실 모형과 신뢰도 이론",
            "IFRS 17 보험계약 기준서",
            "재보험 구조와 리스크 관리",
            "연금수학과 퇴직급여",
        ],
    },
    {
        "title": "산업공학 (Industrial Engineering)",
        "source": "POSTECH IE · 서울대 산업공학",
        "category": "ie",
        "order_index": 12,
        "lectures": [
            "산업공학 개론",
            "선형계획법 (Linear Programming)",
            "정수계획법과 네트워크 최적화",
            "대기행렬 이론 (Queuing Theory)",
            "시뮬레이션 모델링",
            "재고 관리 모델",
            "수요 예측",
            "공급망 관리 (Supply Chain Management)",
            "설비 배치와 자재 흐름",
            "작업 측정과 공정 분석",
            "품질 관리와 통계적 공정 관리 (SPC)",
            "6시그마와 린 생산",
            "프로젝트 관리 (CPM/PERT)",
            "생산 계획 및 일정 관리",
        ],
    },
]


async def seed_courses(db: AsyncSession) -> dict:
    existing_categories = set(
        (await db.execute(select(Course.category))).scalars().all()
    )

    courses_added = 0
    lectures_added = 0

    for data in _COURSES:
        if data["category"] in existing_categories:
            continue

        course = Course(
            title=data["title"],
            source=data["source"],
            category=data["category"],
            order_index=data["order_index"],
        )
        db.add(course)
        await db.flush()

        for i, title in enumerate(data["lectures"], start=1):
            db.add(Lecture(
                course_id=course.id,
                title=title,
                number=i,
                category=data["category"],
            ))
            lectures_added += 1

        courses_added += 1

    if courses_added:
        await db.commit()
        logger.info(f"[Seed] Course {courses_added}개, Lecture {lectures_added}개 삽입 완료")
    else:
        logger.info("[Seed] 모든 카테고리 이미 존재 — 스킵")
    return {"courses": courses_added, "lectures": lectures_added}
