apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stu-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amoocat/self-taught-univ.git
    targetRevision: develop          # develop 브랜치를 감시
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: stu-dev               # dev 전용 네임스페이스
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
