apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: api
          image: yourdockerhub/stu-api:staging-latest
          env:
            - name: DEBUG
              value: "false"
